# =============================================================================
# Template Configuration File for Batch Image Embedding with OpenCLIP
# =============================================================================
# This YAML file specifies all parameters needed for running the embedding script.
# Copy and modify this template for your specific jobs.
# -----------------------------------------------------------------------------

# ---------------------------
# Model Configurations
# ---------------------------
# List one or more models to use for embedding. Each model should have:
#   - name: Model identifier (can be a HuggingFace Hub repo or OpenCLIP model name)
#   - pretrained: Pretrained weights identifier (or null for default)
# For a list of all OpenCLIP supported models and pretrained weights, see:
#   https://github.com/mlfoundations/open_clip#pretrained-models
models:
  bioclip:
    name: hf-hub:imageomics/bioclip-2
    pretrained: null
  # Uncomment and edit below to add more models
  # Vit_L_14:
  #   name: ViT-L-14
  #   pretrained: laion2b_s32b_b82k
  # Vit_bigG_14:
  #   name: ViT-bigG-14
  #   pretrained: laion2b_s39b_b160k

# ---------------------------
# DataLoader Configurations
# ---------------------------
batch_size: 16          # Number of images per batch sent to the model
num_workers: 28         # Number of worker processes for data loading
prefetch_factor: 32     # Number of batches prefetched by each worker
read_batch_size: 128    # Number of rows read from Parquet at a time

# List of columns to read from the Parquet files. 
# These must match the columns present in your data.
read_columns:
  - uuid
  - original_size
  - resized_size
  - image

# ---------------------------
# Output Configurations
# ---------------------------
max_rows_per_file: 500000    # Maximum number of rows per output Parquet file
out_prefix: oc_embed         # Prefix for output files

# =============================================================================
# End of configuration file
# =============================================================================